
/**
These files are autogenerated using gardenbuzz_client/scripts/make_modules.py
DO NOT EDIT THESE FILES!

Re-generate them from the command line:

cd gardenbuzz_client
python ./scripts/make_modules.py src/pages/<page name>/modules_used.json

That will re-build the ./modules directory in the page specified.

*/

import * as Sentry from '@sentry/browser'

import {setConfig as set_config_season }  from '~/modules/season'
import {initialize as init_season }  from '~/modules/season'

export const set_config = (config) =>{
  set_config_season(config)
}
export const initialize = (options) =>{
  if(options.sentry_sdk && options.sentry_sdk.dsn) {
    Sentry.init({ dsn: options.sentry_sdk.dsn })
  }
  init_season(options)
}
