
/**
These files are autogenerated using gardenbuzz_client/scripts/make_modules.py
DO NOT EDIT THESE FILES!

Re-generate them from the command line:

cd gardenbuzz_client
python ./scripts/make_modules.py src/pages/<page name>/modules_used.json

That will re-build the ./modules directory in the page specified.

*/

import {combineReducers} from 'redux'

import season_reducer, { NAME as season_name } from '~/modules/season'

export const rootReducer = combineReducers({
  [season_name]: season_reducer,
})
