<!DOCTYPE html PUBLIC "~//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US"
      xml:lang="en-US">
<head>
  <title><?php echo $page_title; ?></title>
  <meta http-equiv="content-type"
        content="text/html; charset=utf-8"/>
  <link rel="stylesheet" href="basestyle.css" type="text/css"/>
</head>
<body class='pageBody'>

<table border='1' align='center' width='80%' cellspacing='0'
       cellpadding='0'>
<tr>
  <td>
    <table width='100%' border='0' cellspacing='0'
           cellpadding='4' class='topMenuBar'>
    <tr>
      <td width='20%' align='center' class='topMenuCell'>
        <a class='topMenuLink' href='index.php'>Home</a>
      </td>
      <td width='20%' align='center' class='topMenuCell'>
        <a class='topMenuLink' href='addnewappt.php'>
          New Appointment
        </a>
      </td>
      <td width='20%' align='center' class='topMenuCell'>
        <a class='topMenuLink' href='showday.php'>Today</a>
      </td>
      <td width='20%' align='center' class='topMenuCell'>
        <a class='topMenuLink' href='showweek.php'>
          This Week
        </a>
      </td>
      <td width='20%' align='center' class='topMenuCell'>
        <a class='topMenuLink' href='showmonth.php'>
          This Month
        </a>
      </td>
    </tr>
    </table>
  </td>
</tr>
</table>

