version: '2'

volumes:
  tennis_data_dev: {}

services:
#  postgres:
#    container_name: tennisblock-postgres
#    build: ./compose/postgres
#    volumes:
#      - tennis_data_dev:/var/lib/postgresql/data
#      - ./database/backups:/backups
#    environment:
#      - POSTGRES_USER=tennisblock
#      - POSTGRES_DB=tennisblock
#    ports:
#      - "5442:5432"

  mysql:
    container_name: tennis-mysql
    build: ./compose/mysql
    volumes:
      - tennis_data_dev:/var/lib/mysql
      - ./database/backups:/backups
      # You can also modify this to point to your local Dropbox location where the shared
      # backups are stored. For me this is:
      #- "~/Dropbox/Development/tennisblock/msyql/backups:/backups"
    environment:
        - MYSQL_ROOT_PASSWORD=tennisroot
        - MYSQL_DATABASE=tennisblock
        - MYSQL_USER=tennisblock
        - MYSQL_PASSWORD=tennisblock
    ports:
      - "3318:3306"

  smtpd:
    container_name: tennis-smtpd
    build: ./compose/smtpd
    ports:
      - "8026:25"

