version: '3.7'

volumes:
  postgres_data_dev:
  tennis_data_dev:

services:

  postgres:
    container_name: ${NAME:-tennis}-postgres
    build: ./compose/postgres
    volumes:
      #- postgres_data_dev:/var/lib/postgresql/data
      #- ./database/backups:/backups
      # You can also modify this to point to your local Dropbox location where the shared
      # Update .env file to set a location on your system.
      - "${BACKUP_ROOT}:/backups"
      - "${LOCAL_BACKUPS}:/local_backups"
    environment:
      - POSTGRES_USER=tennisblock
      - POSTGRES_DB=tennisblock
    ports:
      - "${PG_PORT:-5432}:5432"

  smtpd:
    container_name: ${NAME:-tennis}-smtpd
    build: ./compose/smtpd
    ports:
      - "${SMTP_PORT:-1035}:25"

  mailhog:
    container_name: ${NAME:-tennis}-hog
    build: ./compose/mailhog
    ports:
      - "${MAILHOG_SMTP:-1025}:1025"
      - "${MAILHOG_HTTP:-8025}:8025"
