version: '2'

volumes:
  postgres_data_dev:
  tennis_data_dev:

services:

  postgres:
    container_name: tennis-postgres
    build: ./compose/postgres
    volumes:
      #- postgres_data_dev:/var/lib/postgresql/data
      #- ./database/backups:/backups
      # You can also modify this to point to your local Dropbox location where the shared
      # Update .env file to set a location on your system.
      - "${SHARED_BACKUPS}:/backups"
      - "${LOCAL_BACKUPS}:/local_backups"
    environment:
      - POSTGRES_USER=tennisblock
      - POSTGRES_DB=tennisblock
    ports:
      - "5443:5432"

  smtpd:
    container_name: tennis-smtpd
    build: ./compose/smtpd
    ports:
      - "8026:25"

