version: '2'

volumes:
  postgres_data_dev: {}
  tennis_data_dev: {}

services:

  postgres:
    container_name: tennis-postgres
    build: ./compose/postgres
    volumes:
      #- postgres_data_dev:/var/lib/postgresql/data
      #- ./database/backups:/backups
      # You can also modify this to point to your local Dropbox location where the shared
      # backups are stored. For me this is:
      - ~/Dropbox (SharperTool)/TennisBlock/database_backups:/backups
      - ./database/backups:/local_backups
      # Enter a custom location called /mybackups that are for your localwork
      #- "~/Dropbox (Big Zeta)/EdLocal/datapages_db:/mybackups"
    environment:
      - POSTGRES_USER=tennisblock
      - POSTGRES_DB=tennisblock
    ports:
      - "5443:5432"

#  mysql:
#    container_name: tennis-mysql
#    build: ./compose/mysql
#    volumes:
#      - tennis_data_dev:/var/lib/mysql
#      - ./database/backups:/backups
#      # You can also modify this to point to your local Dropbox location where the shared
#      # backups are stored. For me this is:
#      #- "~/Dropbox/Development/tennisblock/msyql/backups:/backups"
#    environment:
#        - MYSQL_ROOT_PASSWORD=tennisroot
#        - MYSQL_ROOT_HOST=172.*.*.*
#        - MYSQL_DATABASE=tennisblock
#        - MYSQL_USER=tennisblock
#        - MYSQL_PASSWORD=tennisblock
#    ports:
#      - "3319:3306"

  smtpd:
    container_name: tennis-smtpd
    build: ./compose/smtpd
    ports:
      - "8026:25"

