#!/bin/sh

# This is a bash script version of manage.py..
# All that it does is load the environment (in case you forget)
# and run manage.py
# It's also 3 fewer characters to type.. and in some projects,
# at the root instead of buried.

if [ -z "$VIRTUAL_ENV" ];then
    activate
fi

if [ -z "$VIRTUAL_ENV" ];then
    echo "You must setup a local virtualenv and install requirements first"
    exit 2
fi

pushd tennisblock >> /dev/null
python manage.py "$@"
popd tennisblock >> /dev/null

