#!/bin/sh

# This is a bash script version of manage.py..
# All that it does is load the environment (in case you forget)
# and run manage.py
# It's also 3 fewer characters to type.. and in some projects,
# at the root instead of buried.

pushd tennisblock >> /dev/null
python manage.py "$@"
popd tennisblock >> /dev/null

