#!/bin/sh

port=8002
SECURE=0
while getopts ":p:s" option
do
    case ${option} in
        p) port=${OPTARG};;
        s) SECURE=1;;
    esac
done


base=$(cd $(dirname $0);pwd)
root=$(dirname $(find . -depth -maxdepth 2 -name 'manage.py'))
cd ${root}

pluscheck=$(${base}/.venv3/bin/python manage.py | grep runserver_plus)
runcmd=${pluscheck:-runserver}

if [ ${pluscheck} ];then
    runcmd="runserver_plus"
    if [ ${SECURE} -eq 1 ];then
        echo "Running with secure"
        runcmd="runserver_plus --cert-file ../ssl/private.crt"
    else
        echo "Running as http"
    fi
fi
echo "Run command: ${runcmd}"

while true
do
    ${base}/.venv3/bin/python manage.py ${runcmd} ${port}
    sleep 2
done


