DROP TABLE IF EXISTS WROX_SITE_ACCESS;

CREATE TABLE WROX_SITE_ACCESS (
    ACCESS_TIME  TIMESTAMP        NOT NULL  DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS   INTEGER UNSIGNED NOT NULL,
    REQ_PAGE     VARCHAR(255)     NOT NULL,

    PRIMARY KEY (ACCESS_TIME, IP_ADDRESS)
)
ENGINE=InnoDB DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs;

