# Generated by Django 2.0.8 on 2018-08-31 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TennisUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntrp', models.FloatField(blank=True, default=2.5, null=True)),
                ('micro_ntrp', models.FloatField(blank=True, default=2.5, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tennis_profile.TennisUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
