# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_profile', '0002_auto_20140910_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
    ]
