version: 2.1
orbs:
  cypress: cypress-io/cypress@1.1.0
  aws-white-list-circleci-ip: configure/aws-white-list-circleci-ip@1.0.1

executors:
  container_config:
    working_directory: ~/build
    docker:
      - image: sharpertool/docker_ci_python3:1.5.2
        environment:
          ZIP_PREFIX: tennisblock

      - image: sharpertool/ci_postgis:1.0.1
        environment:
          POSTGRES_PASSWORD: testing-password
          POSTGRES_USER: circleci
          POSTGRES_DB: tennisblock

      - image: sharpertool/smtpd:1.0.1

  container_config_min:
    working_directory: ~/build
    docker:
      - image: sharpertool/docker_ci_python3:1.5.2
        environment:
          ZIP_PREFIX: tennisblock
          DEPLOY_BUCKET: tennisblock.deploy
          DEPLOY_BUCKET_PATH: backend_versions
          APP_DIR: /var/www/tennisblock

references:

  workspace_root: &workspace_root
    ~/build

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  venv_cache_key: &venv_cache_key
    v2-dependency-venv-{{ checksum "requirements/test.txt" }}-{{ checksum "requirements/dev.txt" }}-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/prod.txt" }}

  restore_venv: &restore_venv
    restore_cache:
      keys:
        - *venv_cache_key

  asset_build_cache_key: &asset_build_cache_key
    v1-gulp-build-{{ checksum "webpack_assets/package.json" }}

  restore_asset_build_cache: &restore_asset_build_cache
    restore_cache:
      keys:
        - *asset_build_cache_key

  client_build_cache_key: &client_build_cache_key
    v1-client-build-{{ checksum "client/package.json" }}

  restore_client_build_cache: &restore_client_build_cache
    restore_cache:
      keys:
        - *client_build_cache_key

  disable_strict_type_checking: &disable_strict_type_checking
    run:
      name: Disable strict type checking
      command: |
        mkdir ~/.ssh/
        echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

  persist_manifest: &persist_manifest
    persist_to_workspace:
          root: *workspace_root
          paths:
            - ./manifest.json

  store_manifest: &store_manifest
    store_artifacts:
      path: ./manfest.json
      destination: manifest.json

jobs:
  checkout_code:
    executor: container_config_min
    steps:

      - run:
          name: Avoid hosts unknown for bitbucket
          command: |
            mkdir -p ~/.ssh/
            echo -e "Host bitbucket.org\n  StrictHostKeyChecking no\n" >> ~/.ssh/config

      - checkout

      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  build_venv:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv

      - run:
          name: Install project pip modules
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -U pip
            pip install -r requirements/test.txt --progress-bar off

      - save_cache:
          key: *venv_cache_key
          paths:
            - .venv

  compile_assets:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv
      - *restore_asset_build_cache
      - *attach_workspace

      - run:
          name: Install npm packages for webpack assets using yarn
          command: |
            cd webpack_assets
            yarn install

      - save_cache:
          key: *asset_build_cache_key
          paths:
            - webpack_assets/node_modules

      - run:
          name: Build CSS Assets using Webpack
          command: |
            cd webpack_assets
            environment=production yarn build:ci

      - run:
          name: Show compiled contents of webpack build location
          command: |
            ls -al ./webpack_assets/dist.prod || true
            ls -al ./tennisblock/static || true

      - run:
          name: Copy Webpack compiled dist.prod over to frontend
          command: |
            ./ci_scripts/copy_webpack_assets.sh

      - run:
          name: Show frontend output directories
          command: |
            ls -al ./tennisblock/frontend || true
            ls -al ./tennisblock/frontend/static || true

      - save_cache:
          key: *asset_build_cache_key
          paths:
            - build_assets/node_modules

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./tennisblock/static
            - ./tennisblock/webapp/static
            - ./tennisblock/frontend/static
            - ./tennisblock/frontend/webpack-assets-stats.json
            - ./collectedstatic

  compile_client_code:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv
      - *restore_client_build_cache
      - *attach_workspace

      - run:
          name: Install npm packages for client_build
          command: |
            cd client
            yarn install

      - save_cache:
          key: *client_build_cache_key
          paths:
            - client/node_modules

      - run:
          name: Build CSS Assets using Gulp
          command: |
            cd client
            yarn build_modules
            yarn compile:prod

      - run:
          name: Copy dist.prod over to frontend
          command: |
            client/scripts/copyprod.sh

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./tennisblock/static
            - ./client/dist.prod
            - ./tennisblock/frontend/static
            - ./tennisblock/frontend/webpack-stats.json
            - ./client/src/pages
            - ./collectedstatic

  client_code_tests:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv
      - *restore_client_build_cache
      - *attach_workspace

      - run:
          name: Run tests
          command: |
            cd client
            yarn test

  collectstatic:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv
      - *attach_workspace

      - run:
          name: Show compiled contents of static location
          command: |
            ls -al ./tennisblock/static || true

      - run:
          name: Collect static files
          command: |
            source .venv/bin/activate
            cd tennisblock
            python manage.py collectstatic --noinput --ignore=*.scss
          environment:
            DJANGO_SETTINGS_MODULE: tennisblock.settings.circleci

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./collectedstatic

  pytest:
    executor: container_config
    steps:
      - *restore_repo
      - *restore_venv
      - *attach_workspace

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          command: |
            source .venv/bin/activate
            cd tennisblock
            DJANGO_SETTINGS_MODULE=tennisblock.settings.circleci python manage.py test

  build_zip_file:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv
      - *attach_workspace

      - run:
          name: Build zip deploy file and persist to workspace
          command: |
            mkdir -p zipout
            zipfile=$(./ci_scripts/zipfilename.sh)
            echo "Zip file name:${zipfile}"
            zip -r zipout/${zipfile} \
              collectedstatic/ *.wsgi tennisblock/ scripts/ \
              requirements/ requirements.txt \
              -x \*.pyc -x tennisblock/local_config.py \
              -x tennisblock/.env.local -x tennisblock/.env.test

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - ./zipout

  deploy_to_s3_bucket:
    executor: container_config_min
    steps:
      - *restore_repo
      - *restore_venv
      - *attach_workspace

      - run:
          name: Deploy the zip file to the remote bucket
          command: |
            pwd
            ls -al zipout
            zipfile=$(ls zipout/)xxxxhl
            echo "Deploying ${zipfile} to S3"
            VERSION=${CIRCLE_TAG:-${CIRCLE_SHA1}}
            s3path="s3://${DEPLOY_BUCKET}/${DEPLOY_BUCKET_PATH}/${zipfile}"
            aws s3 cp zipout/${zipfile} ${s3path}

  deploy_to_prod_server:
    executor: container_config_min
    steps:
      - *restore_repo
      - *disable_strict_type_checking
      - *attach_workspace


      - aws-white-list-circleci-ip/add:
          port: 22
          mask: 32
          tag-key: circleci_deploy
          tag-value: deploy_code

      - run:
          name: Add Target Host to config to disable strict type checking
          command: |
            ./ci_scripts/host_config.sh ${DEPLOY_HOST}

      - run:
          name: Show current config value.
          command: |
            ls -al ~
            if [[ -d ~/.ssh ]];then
              cat ~/.ssh/config
            fi

      - run:
          name: Copy zipfile to prod server
          command: |
            ls -al zipout
            zipfile=$(ls zipout/)
            ssh deploy_host "mkdir -p ${APP_DIR}/deploy/"
            scp zipout/${zipfile} deploy_host:${APP_DIR}/deploy/

      - run:
          name: Copy deploy script to server
          command: |
            ./ci_scripts/copy_deploy_script.sh || true
          environment:
            SRC_SCRIPT: site_deploy_zip.sh

      - run:
          name: Run deploy script on prod server
          command: |
            zipfile=$(ls zipout/)
            echo "Deploying zipfile ${zipfile} on server"
            timestamp=$(date +%Y-%m-%d)
            export VERSION=${CIRCLE_TAG:-${timestamp}_${CIRCLE_SHA1}}
            echo "Updating the version to ${VERSION}"
            ssh deploy_host \
              "${APP_DIR}/site_deploy_zip.sh ${zipfile} ${VERSION}"

      - run:
          name: Add Sentry release
          command: |
            export VERSION=$(sentry-cli releases propose-version)
            sentry-cli releases new $VERSION
            sentry-cli releases set-commits --auto $VERSION
            sentry-cli releases files $VERSION upload-sourcemaps ./client/dist.prod
            sentry-cli releases finalize $VERSION
            sentry-cli releases deploys $VERSION new -e test
          environment:
            SENTRY_ORG: sharpertool-vc
            SENTRY_PROJECT: tennisblock

      - aws-white-list-circleci-ip/remove:
          port: 22
          mask: 32
          tag-key: circleci_deploy
          tag-value: deploy_code

workflows:
  version: 2

  build_test_deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore:
                - develop_ci_test
                - packer_test

      - build_venv:
          requires:
            - checkout_code
          filters:
            tags:
              only: /v.*/

      - compile_assets:
          requires:
            - build_venv
          filters:
            tags:
              only: /v.*/

      - compile_client_code:
          requires:
            - compile_assets
          filters:
            tags:
              only: /v.*/
            branches:
              only:
                - develop

      - client_code_tests:
          requires:
            - compile_client_code
          filters:
            tags:
              only: /v.*/
            branches:
              only:
                - develop

      - collectstatic:
          requires:
            - compile_assets
            - compile_client_code
          filters:
            tags:
              only: /v.*/
            branches:
              only:
                - develop

#      - pytest:
#          requires:
#            - build_venv
#            - collectstatic
#          filters:
#            tags:
#              only: /v.*/
#            branches:
#              only:
#                - develop

      - build_zip_file:
          requires:
            - build_venv
            - collectstatic
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - deploy_to_s3_bucket:
          requires:
            - build_zip_file
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - deploy_to_prod_server:
          requires:
            - build_zip_file
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

