# Generated by Django 2.0.8 on 2018-08-31 02:07

import blockdb.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fulltime', models.BooleanField(default=False)),
                ('as_singles', models.BooleanField(default=False)),
                ('canschedule', models.BooleanField(default=False)),
                ('blockcouple', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('court', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('holdout', models.BooleanField(default=False)),
                ('comments', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=40)),
                ('last', models.CharField(max_length=60)),
                ('gender', models.CharField(choices=[('F', 'Gal'), ('M', 'Guy')], max_length=1)),
                ('ntrp', models.FloatField()),
                ('microntrp', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issub', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Meetings')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_partner', to='blockdb.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='blockdb.Player')),
            ],
            options={
                'permissions': (('change_sched', 'Can change the schedule'),),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('courts', models.IntegerField()),
                ('firstcourt', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('blockstart', models.DateField()),
                ('lastdate', models.DateField(null=True)),
                ('blocktime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockmember', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='blockdb.Season')),
            ],
        ),
        migrations.AddField(
            model_name='meetings',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Season'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Meetings'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team1_p1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1_p1', to='blockdb.Player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team1_p2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t1_p2', to='blockdb.Player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team2_p1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2_p1', to='blockdb.Player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='team2_p2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2_p2', to='blockdb.Player'),
        ),
        migrations.AddField(
            model_name='couple',
            name='female',
            field=models.ForeignKey(limit_choices_to=blockdb.models.limit_to_gals, on_delete=django.db.models.deletion.CASCADE, related_name='couple_gal', to='blockdb.Player'),
        ),
        migrations.AddField(
            model_name='couple',
            name='male',
            field=models.ForeignKey(limit_choices_to=blockdb.models.limit_to_guys, on_delete=django.db.models.deletion.CASCADE, related_name='couple_guy', to='blockdb.Player'),
        ),
        migrations.AddField(
            model_name='couple',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Season'),
        ),
        migrations.AddField(
            model_name='availability',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Meetings'),
        ),
        migrations.AddField(
            model_name='availability',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available', to='blockdb.Player'),
        ),
    ]
