# Generated by Django 2.0.8 on 2018-09-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SeasonPlayers',
            new_name='SeasonPlayer',
        ),
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ManyToManyField(related_name='season_player', to='blockdb.Season'),
        ),
    ]
