# Generated by Django 2.0.8 on 2018-09-15 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0002_auto_20180914_1905'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meetings',
            new_name='Meeting',
        ),
    ]
