# Generated by Django 2.0.8 on 2018-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0003_auto_20180914_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last',
        ),
        migrations.AlterField(
            model_name='player',
            name='season',
            field=models.ManyToManyField(blank=True, related_name='season_player', to='blockdb.Season'),
        ),
    ]
