# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-09 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0005_auto_20150103_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='couple',
            name='as_singles',
            field=models.BooleanField(default=False),
        ),
    ]
