# Generated by Django 2.0.8 on 2018-09-21 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0005_remove_player_season'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couple',
            unique_together={('season', 'male', 'female')},
        ),
    ]
