# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0006_couple_as_singles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('F', 'Gal'), ('M', 'Guy')], max_length=1),
        ),
    ]
