# Generated by Django 2.0.8 on 2018-08-30 03:27

import blockdb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0007_auto_20180110_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='female',
            field=models.ForeignKey(limit_choices_to=blockdb.models.limit_to_gals, on_delete=django.db.models.deletion.CASCADE, related_name='couple_gal', to='blockdb.Player'),
        ),
        migrations.AlterField(
            model_name='couple',
            name='male',
            field=models.ForeignKey(limit_choices_to=blockdb.models.limit_to_guys, on_delete=django.db.models.deletion.CASCADE, related_name='couple_guy', to='blockdb.Player'),
        ),
    ]
