# Generated by Django 2.1.2 on 2019-01-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0007_meeting_court_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(through='blockdb.SeasonPlayer', to='blockdb.Player'),
        ),
        migrations.AlterField(
            model_name='season',
            name='lastdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasonplayer',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Season'),
        ),
    ]
