# Generated by Django 2.1.2 on 2019-01-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0008_auto_20190105_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='players',
            field=models.ManyToManyField(related_name='seasons', through='blockdb.SeasonPlayer', to='blockdb.Player'),
        ),
    ]
