# Generated by Django 2.2.4 on 2019-09-05 01:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0010_auto_20190108_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabiliy', to='blockdb.Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockdb.Season')),
            ],
        ),
    ]
