# Generated by Django 2.2.4 on 2019-09-05 01:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0011_playeravailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeravailability',
            name='availability',
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='available',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='playeravailability',
            name='scheduled',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=[], size=None),
        ),
    ]
