# Generated by Django 2.2.4 on 2019-09-05 01:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0012_auto_20190904_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeravailability',
            name='available',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='playeravailability',
            name='played',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='playeravailability',
            name='scheduled',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=list, size=None),
        ),
    ]
