# Generated by Django 2.2.4 on 2019-09-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0013_auto_20190904_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_index',
            field=models.IntegerField(default=0),
        ),
    ]
