# Generated by Django 2.2.4 on 2019-09-07 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0014_meeting_meeting_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_index',
        ),
        migrations.AddField(
            model_name='meeting',
            name='season_index',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='playeravailability',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='blockdb.Player'),
        ),
    ]
