# Generated by Django 2.2.4 on 2019-09-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0017_auto_20190910_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleverify',
            name='sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
