# Generated by Django 2.2.4 on 2019-09-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0018_scheduleverify_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleverify',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='scheduleverify',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='blockdb.Schedule'),
        ),
    ]
