# Generated by Django 2.2.4 on 2019-09-11 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0020_auto_20190910_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleverify',
            name='id',
        ),
        migrations.AlterField(
            model_name='scheduleverify',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to='blockdb.Schedule'),
        ),
    ]
