# Generated by Django 2.2.4 on 2019-09-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0021_auto_20190910_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleverify',
            name='received_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
