# Generated by Django 2.2.4 on 2019-09-15 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0022_scheduleverify_received_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleverify',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification', serialize=False, to='blockdb.Schedule'),
        ),
    ]
