# Generated by Django 2.2.4 on 2019-09-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0024_auto_20190916_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleverify',
            name='sent_to',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='send email address'),
        ),
    ]
