# Generated by Django 2.2.4 on 2019-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0025_auto_20190916_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleverify',
            name='confirmation_type',
            field=models.CharField(choices=[('C', 'Confirm'), ('R', 'Reject'), ('A', 'Awaiting Response'), ('N', 'Not Sent')], default='N', max_length=1),
        ),
    ]
