# Generated by Django 2.2.6 on 2019-12-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockdb', '0026_auto_20190916_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pair_index',
            field=models.IntegerField(default=-1),
        ),
    ]
