<?php
/**
 * dbconninfo.inc
 *
 * Author: Marc Wandschneider:  2005-03-15
 *
 * This file contains constants and information used to connect
 * to our database for the appointments web application sample.
 */

define('DB_HOST', 'ed.deepbondi.net');
#define('DB_USER', 'fnt_user');
define('DB_USER', 'fntennis');
define('DB_PASS', 'P5HJTdHt5dR2t9Q2');
define('DB_DBASE', 'friday_tennis');

?>
