DROP TABLE IF EXISTS WROX_CALENDAR;

CREATE TABLE WROX_CALENDAR (
    EVENT_ID      INTEGER UNSIGNED     NOT NULL  AUTO_INCREMENT,
    EVENT_NAME    VARCHAR(100)         NOT NULL,
    EVENT_TSTAMP  TIMESTAMP            NOT NULL,
    NOTIFY        TINYINT(1) UNSIGNED  NOT NULL  DEFAULT 0,
    
    PRIMARY KEY (EVENT_ID)
)
ENGINE=MyISAM DEFAULT CHARACTER SET latin1
    COLLATE latin1_general_cs;
