
/**
These files are autogenerated using gardenbuzz_client/scripts/make_modules.py
DO NOT EDIT THESE FILES!

Re-generate them from the command line:

cd gardenbuzz_client
python ./scripts/make_modules.py src/pages/<page name>/modules_used.json

That will re-build the ./modules directory in the page specified.

*/

import { fork } from 'redux-saga/effects'

import { rootSaga as schedule_root } from '~/modules/schedule'
import { rootSaga as teams_root } from '~/modules/teams'

export function* rootSaga() {
  yield fork(schedule_root)
  yield fork(teams_root)
}
