#!/usr/bin/env bash

if [[ $# -eq 0 ]];then
    echo "usage:"
    echo "  $0 <backup-file>"
    echo " "

    docker-compose exec postgres list-backups
    exit 1

fi

BACKUPFILE=$1

docker-compose exec postgres restore ${BACKUPFILE}
./manage migrate
./manage add_initial_home
./manage add_initial_about

