#!/usr/bin/env bash

scripts=$(cd $(dirname $0);pwd)
root=$(cd $(dirname $0);cd ..;pwd)

echo "Script dir: ${scripts}"
echo "Root dir: ${root}"

if [[ $# -eq 0 ]];then
    echo "usage:"
    echo "  $0 <backup-file>"
    echo " "

    #docker-compose exec postgres list-backups
    exit 1

fi

BACKUPFILE=$1

docker-compose exec postgres restore ${BACKUPFILE}
./manage migrate
./manage localize_sites
./manage add_initial_home
